Testing new actions

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -11,8 +11,19 @@ on:
 env:
   APP_NAME: appcat
   COMPONENT_REPO: kidswiss/component-appcat
+  PUSH_UPBOUND: "False"
+  PUSH_PACKAGE: "True"
+  PUSH_IMAGE: "True"
 
 jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'master' && (github.head_ref != 'develop' || contains(github.event.pull_request.labels.*.name, 'hotfix') )
+        run: |
+          echo "ERROR: You can only merge to master from develop or hotfixes."
+          exit 1
   check-labels:
     # Act doesn't set a pull request number by default, so we skip if it's 0
     if: github.event.pull_request.number != 0
@@ -21,7 +32,7 @@ jobs:
     steps:
       - uses: docker://agilepathway/pull-request-label-checker:v1.6.51
         with:
-          one_of: breaking,enhancement,bug
+          one_of: major,minor,patch,documentation,dependency
           repo_token: ${{ secrets.GITHUB_TOKEN }}
   publish-branch-images:
     if: github.event.action != 'closed'
@@ -43,6 +54,11 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-go-
 
+      - name: Extract escaped branch name
+        shell: bash
+        run: echo "branch=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | sed 's/\//_/g' )" >> $GITHUB_OUTPUT
+        id: extract_branch
+
       - name: Login to GHCR
         uses: docker/login-action@v3
         with:
@@ -50,13 +66,27 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build branch and push AppCat
-        run: make docker-push-branchtag
+      - name: Build branch and push image
+        if: env.PUSH_IMAGE == 'true'
+        run: make docker-push-branchtag -e IMG_TAG="${{ steps.extract_branch.outputs.branch }}"
 
-      - name: Build branch and push Functions
-        run: make function-push-package-branchtag
-  open-pr-component:
-    if: github.event.action == 'opened'
+      - name: Build branch and push package
+        if: env.PUSH_PACKAGE == 'True'
+        run: make package-push-branchtag -e IMG_TAG="${{ steps.extract_branch.outputs.branch }}"
+
+      - name: Login to Upbound
+        if: env.PUSH_UPBOUND == 'true'
+        uses: docker/login-action@v3
+        with:
+          registry: xpkg.upbound.io
+          username: ${{ secrets.UPBOUND_MARKETPLACE_PUSH_ROBOT_USR }}
+          password: ${{ secrets.UPBOUND_MARKETPLACE_PUSH_ROBOT_PSW }}
+
+      - name: Build branch and push package to upbound
+        if: env.PUSH_UPBOUND == 'true' && env.PUSH_PACKAGE == 'true'
+        run: make package-push-branchtag -e IMG_TAG="${{ steps.extract_branch.outputs.branch }}" -e IMG_REPO=xpkg.upbound.io
+
+  open-or-update-pr-component:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -64,6 +94,7 @@ jobs:
         with:
           repository: ${{ env.COMPONENT_REPO }}
           token: ${{ secrets.GITHUB_TOKEN }}
+          history: 0
 
       - name: Extract branch name
         shell: bash
@@ -83,32 +114,46 @@ jobs:
         run: |
           make gen-golden-all
 
+      - name: Check if it's a hotfix
+        id: hotfix_check
+        run: |
+          [ ${{ contains(github.event.pull_request.labels.*.name, 'hotfix') }} ] && echo "base=master" >> $GITHUB_OUTPUT || echo "base=develop" >> $GITHUB_OUTPUT
+
       - name: Create Pull Request
-        uses: peter-evans/create-pull-request@v3
+        uses: peter-evans/create-pull-request@v7
+        id: cpr
         with:
           token: ${{ secrets.COMPONENT_ACCESS_TOKEN }}
-          title: 'PR for ${{ env.APP_NAME }} on ${{ steps.extract_branch.outputs.branch }}'
-          body: "${{ github.event.pull_request.body}}\nLink: ${{ github.event.pull_request.url }}"
+          title: ${{ github.event.pull_request.title }}
+          body: "${{ github.event.pull_request.body}}\nLink: ${{ github.event.pull_request.html_url }}"
           branch: "${{ env.APP_NAME }}/${{ github.event.pull_request.number }}/${{ steps.extract_branch.outputs.branch }}"
-          base: master
+          base: ${{ steps.hotfix_check.outputs.base }}
           draft: false
+
+      - uses: tzkhan/pr-update-action@v2
+        with:
+          repo-token: "${{ secrets.GITHUB_TOKEN }}"
+          body-template: |
+            Component PR: ${{ steps.cpr.outputs.pull-request-url }}
+          body-update-action: 'suffix'
+          body-uppercase-base-match: false
   create-release:
     if: github.event.pull_request.merged
     runs-on: ubuntu-latest
     steps:
-      - name: Check for bug label
-        if: contains(github.event.pull_request.labels.*.name, 'bug')
-        id: bug
+      - name: Check for patch label
+        if: contains(github.event.pull_request.labels.*.name, 'patch') || contains(github.event.pull_request.labels.*.name, 'dependency') || contains(github.event.pull_request.labels.*.name, 'documentation')
+        id: patch
         run: |
           echo "set=true" >> $GITHUB_OUTPUT
-      - name: Check for enhancement label
-        if: contains(github.event.pull_request.labels.*.name, 'enhancement')
-        id: enhancement
+      - name: Check for minor label
+        if: contains(github.event.pull_request.labels.*.name, 'minor')
+        id: minor
         run: |
           echo "set=true" >> $GITHUB_OUTPUT
-      - name: Check for breaking label
-        if: contains(github.event.pull_request.labels.*.name, 'breaking')
-        id: breaking
+      - name: Check for major label
+        if: contains(github.event.pull_request.labels.*.name, 'major')
+        id: major
         run: |
           echo "set=true" >> $GITHUB_OUTPUT
 
@@ -135,36 +180,38 @@ jobs:
         run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
         id: extract_branch
 
+      # We only run this if any of the release tags is set.
+      # For docs and deps we don't do automagic releases
       - name: Increase Tag
         id: tag
         run: |
-          bug=${{ steps.bug.outputs.set }}
-          enhancement=${{ steps.enhancement.outputs.set }}
-          breaking=${{ steps.breaking.outputs.set }}
+          patch=${{ steps.patch.outputs.set }}
+          minor=${{ steps.minor.outputs.set }}
+          major=${{ steps.major.outputs.set }}
 
-          breaking_ver=$(echo '${{ env.TAG_VERSION }}' | cut -d "." -f1)
-          enhancement_ver=$(echo '${{ env.TAG_VERSION }}' | cut -d "." -f2)
-          bug_ver=$(echo '${{ env.TAG_VERSION }}' | cut -d "." -f3)
+          major_ver=$(echo '${{ env.TAG_VERSION }}' | cut -d "." -f1)
+          minor_ver=$(echo '${{ env.TAG_VERSION }}' | cut -d "." -f2)
+          patch_ver=$(echo '${{ env.TAG_VERSION }}' | cut -d "." -f3)
 
-          breaking_ver="${breaking_ver:1}"
+          major_ver="${major_ver:1}"
 
-          # Check for bug label
-          [ ! -z "$bug" ] && [ -z "$enhancement" ] && [ -z "$breaking" ] && ((bug_ver++)) || true
+          # Check for patch label
+          [ ! -z "$patch" ] && [ -z "$minor" ] && [ -z "$major" ] && ((patch_ver++)) || true
 
-          # check for enhancement label
-          if [ ! -z "$enhancement" ] && [ -z "$breaking" ]; then
-            ((enhancement_ver++))
-            bug_ver=0
+          # check for minor label
+          if [ ! -z "$minor" ] && [ -z "$major" ]; then
+            ((minor_ver++))
+            patch_ver=0
           fi
 
-          # Check for breaking label
-          if [ ! -z "$breaking" ]; then
-            ((breaking_ver++))
-            enhancement_ver=0
-            bug_ver=0
+          # Check for major label
+          if [ ! -z "$major" ]; then
+            ((major_ver++))
+            minor_ver=0
+            patch_ver=0
           fi
 
-          tag="v$breaking_ver.$enhancement_ver.$bug_ver"
+          tag="v$major_ver.$minor_ver.$patch_ver"
           echo "new tag $tag"
           git tag $tag
           git push --tags
